# Generated by Django 4.2.2 on 2023-07-19 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercicio',
        ),
    ]
