# Generated by Django 4.2.2 on 2023-07-19 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercicio',
            table='EXERCICIO',
        ),
    ]
